### verify login
GET http://localhost:4000/api/user/verify
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkNThlOGRmZGNlMjBiYmQ5Iiwicm9sZXMiOlsiVVNFUiJdLCJuYW1lIjoiUGl5dXNoIE5hZG9kYSIsImVtYWlsIjoicGl5dXNoQHV0dC5jb20iLCJpYXQiOjE2MzM5NDk2NjgsImV4cCI6MTYzNDU1NDQ2OH0.GSjL7OST95C7js5TUGsXYYnAgQkpIROmjgIOD5-NMLk
