### verify login
GET http://localhost:4000/api/user/verify
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhN2IxNzE0MjU4NDI0NGFmIiwicm9sZXMiOlsiVVNFUiIsIkFETUlOIl0sIm5hbWUiOiJQaXl1c2ggTmFkb2RhIiwiZW1haWwiOiJwaXl1c2hAdXR0LmNvbSIsImlhdCI6MTYzMzg5NjkyNywiZXhwIjoxNjM0NTAxNzI3fQ.xJXpAD913l-vsh2B2VwWcufuQ8tMVLzLYSRWijKOb7Q
