POST http://localhost:4000/api/scrum/set
Content-Type: application/json

{
  "userId":"6f77243707267307",
  "attendance": true,
  "thaCount": 55,
  "thaLink": "https://github.com/untitled-team-101/devsnest-backend/pull/4/files",
  "backlog": "distro hopping",
  "activity": "nacha",
  "rating": 4,
  "sawClass": false
}

###

PUT http://localhost:4000/api/scrum/set
Content-Type: application/json

{
  "userId": "6f77243707267307",
  "thaCount": 69
}
