POST http://localhost:4000/api/scrum/set
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyMmJhNTFhMmVmNDVkODcyIiwiZW1haWwiOiJHb2JsaW5AZGV2c25ldC5jb20iLCJuYW1lIjoiR29ibGluIFNhbmdlciIsInJvbGUiOiJbXCJVU0VSXCJdIiwiaWF0IjoxNjMzODAyMDQ5LCJleHAiOjE2MzQ0MDY4NDl9.LReF0WCxst3-QvSXw4CMSDjAVf2S7ecvS8ZdZOaFxPU

{
  "userId":"22ba51a2ef45d872",
  "attendance": true,
  "thaCount": 55,
  "thaLink": "https://github.com/untitled-team-101/devsnest-backend/pull/4/files",
  "backlog": "distro hopping",
  "activity": "nacha",
  "rating": 4,
  "sawClass": false
}

###

PUT http://localhost:4000/api/scrum/set
Content-Type: application/json

{
  "userId": "667a8c748b60ec88",
  "thaCount": 69
}

###

POST http://localhost:4000/api/scrum/attendance
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjNjUyYTVhNDg5OTFkNjhiIiwicm9sZSI6IltcIlVTRVJcIixcIlRMXCJdIiwibmFtZSI6IlBpeXVzaCBOYWRvZGEiLCJlbWFpbCI6InBpeXVzaEB1dC5jb20iLCJpYXQiOjE2MzM3OTk3MzAsImV4cCI6MTYzNDQwNDUzMH0._P2rXCf861Efvnav0grdbcAuRD4657b0krsTo2wbo9M

{
  "userId": "667a8c748b60ec88",
  "attendance": true
}
