###
POST http://localhost:4000/api/team/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiM2IzYzFkMjUwYzlkZTUxIiwicm9sZXMiOlsiVVNFUiIsIkFETUlOIl0sIm5hbWUiOiJQaXl1c2ggTmFkb2RhIiwiZW1haWwiOiJwaXl1c2hAdXQuY29tIiwiaWF0IjoxNjMzODU0NjYyLCJleHAiOjE2MzQ0NTk0NjJ9.ySHmaFkUliRcCSavxUpRQQ67OfYvyqgqhvWk2-D9-yc

{
  "name": "Untitled 2"
}

###
PUT http://localhost:4000/api/team/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiM2IzYzFkMjUwYzlkZTUxIiwicm9sZXMiOlsiVVNFUiIsIkFETUlOIl0sIm5hbWUiOiJQaXl1c2ggTmFkb2RhIiwiZW1haWwiOiJwaXl1c2hAdXQuY29tIiwiaWF0IjoxNjMzODU0NjYyLCJleHAiOjE2MzQ0NTk0NjJ9.ySHmaFkUliRcCSavxUpRQQ67OfYvyqgqhvWk2-D9-yc

{
  "teamId": "3754dc4a4213",
  "userId": "b3b3c1d250c9de51"
}

###
GET http://localhost:4000/api/team/members?teamId=3754dc4a4213&idOnly=0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiM2IzYzFkMjUwYzlkZTUxIiwicm9sZXMiOlsiVVNFUiIsIkFETUlOIl0sIm5hbWUiOiJQaXl1c2ggTmFkb2RhIiwiZW1haWwiOiJwaXl1c2hAdXQuY29tIiwiaWF0IjoxNjMzODU0NjYyLCJleHAiOjE2MzQ0NTk0NjJ9.ySHmaFkUliRcCSavxUpRQQ67OfYvyqgqhvWk2-D9-yc
