###
POST http://localhost:4000/api/team/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjNzQwZWI1MWM1MGE4ZGI2Iiwicm9sZXMiOlsiVVNFUiIsIkFETUlOIl0sIm5hbWUiOiJQaXl1c2ggTmFkb2RhIiwiZW1haWwiOiJwaXl1c2RoQGRldnNuZXQuY29tIiwiaWF0IjoxNjMzODc4ODA4LCJleHAiOjE2MzQ0ODM2MDh9.9C1-18SDOUv38Yg7f7JKCes6Y7E-nvXAI3tANPBLDIY

{
  "name": "Untitled 2"
}

###
PUT http://localhost:4000/api/team/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjNzQwZWI1MWM1MGE4ZGI2Iiwicm9sZXMiOlsiVVNFUiIsIkFETUlOIl0sIm5hbWUiOiJQaXl1c2ggTmFkb2RhIiwiZW1haWwiOiJwaXl1c2RoQGRldnNuZXQuY29tIiwiaWF0IjoxNjMzODc4ODA4LCJleHAiOjE2MzQ0ODM2MDh9.9C1-18SDOUv38Yg7f7JKCes6Y7E-nvXAI3tANPBLDIY

{
  "teamId": "84d438d3026e",
  "userId": "2f894c51f2d5d53c"
}

###

GET http://localhost:4000/api/team/members?teamId=84d438d3026e&idOnly=0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjNzQwZWI1MWM1MGE4ZGI2Iiwicm9sZXMiOlsiVVNFUiIsIkFETUlOIl0sIm5hbWUiOiJQaXl1c2ggTmFkb2RhIiwiZW1haWwiOiJwaXl1c2RoQGRldnNuZXQuY29tIiwiaWF0IjoxNjMzODc4ODA4LCJleHAiOjE2MzQ0ODM2MDh9.9C1-18SDOUv38Yg7f7JKCes6Y7E-nvXAI3tANPBLDIY
