### register user
POST http://localhost:4000/api/user/register
Content-Type: application/json

{
  "name": "Piyush Nadoda",
  "email": "piyush@ut.com",
  "password": "Bahubali@123",
  "confirmPassword": "Bahubali@123"
}

### login user
POST http://localhost:4000/api/user/login
Content-Type: application/json

{
  "name": "TanmayVaish",
  "email": "piyush@ut.com",
  "password": "Bahubali@123",
  "confirmPassword": "Bahubali@123"
}

### verify login
GET http://localhost:4000/api/user/verify
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjNjUyYTVhNDg5OTFkNjhiIiwicm9sZSI6IltcIlVTRVJcIixcIlRMXCJdIiwibmFtZSI6IlBpeXVzaCBOYWRvZGEiLCJlbWFpbCI6InBpeXVzaEB1dC5jb20iLCJpYXQiOjE2MzM3OTgxMzksImV4cCI6MTYzNDQwMjkzOX0.X4RG0A0VDmJcuJnLHKbgOWpcYm2D53LiH8DMTI7qEs0
###
